stages: [ Reports, Build, Push ]

default:
  timeout: 1h 30m

include:
  - local: "/.gitlab/ci/global.gitlab-ci.yml"

  - local: "/.gitlab/ci/base.gitlab-ci.yml"

  - local: "/.gitlab/ci/lint/docker.yml"

  - local: "/.gitlab/ci/build/docker.yml"

  - local: "/.gitlab/ci/push/gitlab-registry.yml"

workflow:
  rules:
    - if: $PIPELINE_DISABLE == "true"
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|merge_request_event)$/'
      when: never
    - when: always

variables:
  GIT_DEPTH: "20"
  GIT_SUBMODULE_STRATEGY: "none"
  